#税收说明:  每笔商品的上架和买卖都会被服务器收取指定的税务作为手续费   税收最大为100即为100%
#税务配置and店铺等级  可以无限量的自定义但是推荐不超过9个,不然可能会出现位置错误
#最高上架商品种类 每种物品算一种   上线为:54种  即为9*6  插件后续维护会增减到无限
#激活积分  即销售指定金额后达到的店铺等级   可以利用店铺等级增加商品种类数量
#是否开启点券交易模式   即使用PlayerPoints进行商品的交易
#DeBug模式请勿随意开启!
DeBug: false
天猫配置:
  创建店铺所需手续费: 1000
  更改店铺名称手续费: 1000
  店铺名称中不可使用的字符:
    - 国王
    - op
    - 腐竹
等级:
  青铜店铺:
    税收: 50
    最高上架商品种类: 10
    激活积分: 0
    是否开启点券交易模式: false
  白银店铺:
    税收: 45
    最高上架商品种类: 20
    激活积分: 1000
    是否开启点券交易模式: false
  黄金店铺:
    税收: 40
    最高上架商品种类: 30
    激活积分: 1000
    是否开启点券交易模式: true